class LOCATORS:
    url = "https://mail.ukr.net/desktop/login"
    login_input = "input[name='login']"
    mail_address = "andrii_test"
    domain_name = "@ukr.net"
    password_input = "input[name='password']"
    password = "bezkrovnyy"
    submit_button = "[type=submit]"
    letter_button = "//button[@class='default compose']"
    mail_field = "input[name='toFieldInput']"
    subject = "input[name='subject']"
    subject_text = "It is a test"
    test_text = "Hello, Andrii"
    text_field = "//*[@id='mce_0_ifr']"
    send_button = "button[class='default send']"
    back_button = "button[class='action']"
    open_mail_button = "//*[text()='Andrii Bezkrovnyy']"
    search_text = "div[class='readmsg__body']"